name: Node.js CI and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependenciess
      - run: npm ci

      # Build the application
      # - run: npm run build --if-present

      # Deploy to the server using SSH
      - name: Deploy to Server via SSH
        if: ${{ success() }} # Only run if previous steps succeed
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to the app directory or clone repo if not exists
            if [ ! -d "/var/www/node-ts-testing" ]; then
              git clone https://github.com/${{ github.repository }} /var/www/node-ts-testing
            fi
            cd /var/www/node-ts-testing

            # Pull latest changes and install dependencies
            git pull origin master
            npm install

            # # Restart application using PM2
            #  pm2 start src/server.ts --name "aasim"

            pm2 start src/server.ts --name "aasim" --interpreter ts-node

